apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "fraud-detection.fullname" . }}-worker-scaledobject
spec:
  scaleTargetRef:
    name: {{ include "fraud-detection.fullname" . }}-xai-worker
  pollingInterval: 10
  cooldownPeriod: 300
  minReplicaCount: 0
  maxReplicaCount: {{ .Values.worker.maxReplicas | default 10 }}
  triggers:
    - type: redis
      metadata:
        address: {{ .Release.Name }}-redis-master:6379
        listName: celery
        listLength: "10"
        activationListLength: "5"