apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "fraud-detection.fullname" . }}-worker-scaler
spec:
  scaleTargetRef:
    name: {{ .Values.worker.name }}
  minReplicaCount: 0
  maxReplicaCount: {{ .Values.worker.maxReplicas | default 10 }}
  pollingInterval: 15
  cooldownPeriod: 30
  triggers:
  - type: redis
    metadata:
      address: redis://{{ include "fraud-detection.fullname" . }}-redis-master:6379
      listName: celery
      listLength: "5"
      enableTLS: "false"