global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'fraud-api'
    static_configs:
      - targets: ['api:8000']

  - job_name: 'xai-worker'
    static_configs:
      - targets: ['xai-worker:8001']

  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8888']
